### ISSUE TITLE
Issue with help text in Signup page template

### ISSUE THREAD

**Issue by rohitgehe05** [timonweb/django-bulma#12]
Hi @timonweb, firstly really really great job on the Django Bulma integration. Really love the work you've put into this.

I am however getting a formatting issue when I am trying to render the Signup page:

I am attaching the screenshot of what I mean.

The help text below the Password field is not getting rendered properly. I think the issue is because of this [template file](https://github.com/timonweb/django-bulma/blob/master/bulma/templates/bulma/forms/field.html) 

<img width="782" alt="screen shot 2018-01-31 at 6 07 50 pm" src="https://user-images.githubusercontent.com/18504667/35624170-353805c0-06b4-11e8-8f28-c6d6b592587c.png">

**Comment by timonweb** [comment]
Hey, what package do you use for the sign up? Is it regular Django or django-allauth? Here's what I get with django-allauth:

![screenshot](https://user-images.githubusercontent.com/483900/35678883-58c659aa-0755-11e8-8f84-16cc342354f6.png)

**Comment by timonweb** [comment]
Make sure you use latest Django bulma version which is 0.3.4

**Comment by synw** [comment]
Its nice to have Django Allauth support, this is appreciated. I did not notice it was available. Maybe it could be good to mention it in the readme next to "account templates"

**Comment by timonweb** [comment]
@synw good notice, updated the readme.

**Comment by rohitgehe05** [comment]
Hey @timonweb - I am using the latest version of Django Bulma which is 0.3.4 and yes I am using regular Django Auth. Not tried with Allauth yet.

**Comment by timonweb** [comment]
@rohitgehe05 so I guess you've created your own signup form / view then. Could you paste your form html code here?

**Comment by rohitgehe05** [comment]
Hey, these are my views.

```
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'
```

I over-rode the default template to try to debug the problem but no dice. Pasting the HTML below:

```
{% extends "account/base.html" %}

{% load i18n bulma_tags %}

{% block title %}{% trans "Signup" %}{% endblock %}
{% block content_title %}<h1 class="title">{% trans "Sign Up" %}</h1>{% endblock %}

{% block content %}

  <p class="content">Already have an account? Then please <a href="{% url 'login' %}">sign in</a>.</p>

  <form class="signup" id="signup_form" method="post" action="{% url 'account_signup' %}">
    {% csrf_token %}
    {{ form|bulma }}
    {% if redirect_field_value %}
      <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
    {% endif %}
    <button type="submit" class="button is-primary">{% trans "Sign Up" %}</button>
  </form>

{% endblock %}
```

**Comment by rohitgehe05** [comment]
If I change the `template_name` in the views to `account/signup.html`, it has the same issue. Attaching the screenshot below if I change it to the default template.

<img width="716" alt="screen shot 2018-02-01 at 10 56 58 pm" src="https://user-images.githubusercontent.com/18504667/35693154-4ba77f44-07a3-11e8-84e6-d398b4c11ab7.png">

**Comment by rohitgehe05** [comment]
When using Chrome Devtools, it shows that the list `ul` that is rendered isn't inheriting the `class="help"` style.

<img width="1272" alt="screen shot 2018-02-01 at 10 59 24 pm" src="https://user-images.githubusercontent.com/18504667/35693277-b159308a-07a3-11e8-888a-7dc655b60409.png">

**Comment by hozRifai** [comment]
the same problem here, is it working fine with django-allauth?
hopefully, you will find enough time to solve this issue.

**Comment by cjadeveloper** [comment]
Could you solve it? What I did was to redefine the method "_password_validators_help_text_html" to add the class "help" in the ul tag. I pass it to you in a Gist so you can see.
https://gist.github.com/cjadeveloper/ff5fcf3d828d3b7635f9dd0e8ed13a3b

**Comment by cjadeveloper** [comment]
> Could you solve it? What I did was to redefine the method "_password_validators_help_text_html" to add the class "help" in the ul tag. I pass it to you in a Gist so you can see.
> https://gist.github.com/cjadeveloper/ff5fcf3d828d3b7635f9dd0e8ed13a3b
> 
> ![image](https://user-images.githubusercontent.com/2917217/47064603-7e6b1480-d1b6-11e8-9133-1746c8179736.png)

Another thing you can do is fork off Tim's repository and modify the template_tag. @timonweb used Django 1.11 and, apparently, you are using Django 2.x because from version 2.x of Django they Replaced <p> tag with <div> in admin help texts [Fixed #27207](https://github.com/django/django/commit/2d26b4637f0318736955b54b34f270fe9500f795) . That's why the <ul> tag is left out of the paragraph. It's what I did to adapt Tip's bulma_tag for version 2.0.8 of Django that I was using in a project. If you need help with this, let me know.

**Comment by cjadeveloper** [comment]
Another thing you can do is fork off Tim's repository and modify the template_tag. @timonweb used Django 1.11 and, apparently, you are using Django 2.x because from version 2.x of Django they Replaced <p> tag with <div> in admin help texts [Fixed #27207](https://github.com/django/django/commit/2d26b4637f0318736955b54b34f270fe9500f795) . That's why the <ul> tag is left out of the paragraph. It's what I did to adapt Tip's bulma_tag for version 2.0.8 of Django that I was using in a project. If you need help with this, let me know.

**Comment by timonweb** [comment]
Guys just to let you know, I'm listening, just been busy with the work recently, planning to comeback soon and take care of all the fixes, thanks for posting them!

**Comment by timonweb** [comment]
Fixed, I see the messages in red now.

**Comment by sebastianvdn** [comment]
hn
