### ISSUE TITLE
Broken translation in allauth templates

### ISSUE THREAD

**Issue by NicolasLM** [timonweb/django-bulma#25]
I have noticed that some translations in `allauth/account` are broken after overriding them with `bulma/account`.

See for instance `If you have not created an account yet, then please sign up first.` in `bulma/account/login.html`.

From what I can tell it's because templates in `bulma/account` have slightly different line breaks and whitespaces, making the string different enough that the i18n machinery is not able to match them.

**Comment by timonweb** [comment]
If you can do a PR that would help to push this issue.

**Comment by timonweb** [comment]
Allauth support has been dropped, closing this.
