### ISSUE TITLE
Error running python manage.py bulma install on rasp pi 

### ISSUE THREAD

**Issue by LoLL0** [timonweb/django-bulma#28]
Hi all, 
I'm trying to install django-bulma in my django project. 

After I executed "python manage.py copy_bulma_static_into_project" on my rasp pi, I had this issue: 

FileNotFoundError [Errno 2] no such file or directory 'npm'

Could anyone try to help me?

**Comment by timonweb** [comment]
Bulma needs node.js in order to compile. npm is a package manager for node.js. You need to install node.js on your system.

**Comment by LoLL0** [comment]
Hi Tim, 

thank you for the reply. I figured I had to use npm. 
I have another question: sinceI already use Python virtualenv as sandbox, I'd like know if is it possible work with django-bulma ( that needs npm as you told me) with the virtuarlenv? 

Regards, 

Lo

**Comment by timonweb** [comment]
Hi Lo

NPM doesn't care about virtualenv. It's installed globally, so you should be able to access it from virtualenv without any issues. Just make sure that `npm` can be called via command line and it should work just fine.

**Comment by LoLL0** [comment]
Hi Tim, 

thanks for the suggestions, I did it!!

**Comment by timonweb** [comment]
Hi Lo, I'm glad it's working! Closing this one then.
