### ISSUE TITLE
login template is not working

### ISSUE THREAD

**Issue by bobman38** [timonweb/django-bulma#3]
I am using django 1.11.5 with python 3.5.3

When going on the /login url that is using the **registration/login.html** I have the following error:

``'dict' object has no attribute 'flatten'``

It seems to be linked to ``context = context.flatten() `` in **bulma_tags.py**

My context seems ok ?

Variable | Value
-- | --
context | ``{'classes': {'label': '', 'single_value': '', 'value': ''},  'form': <AuthenticationForm bound=False, valid=False, fields=(username;password)>}``

**Comment by timonweb** [comment]
Fixed, pls check and close if it's fine now. I've also pushed 0.0.3 to PYPI with the fix and bulma upgrade to 0.6.0

**Comment by bobman38** [comment]
Good thanks :+1: 
Just need to have a base.html template at root level but I am ok with that,
