### ISSUE TITLE
Navbar-burger can't work in django's render return.

### ISSUE THREAD

**Issue by Huanghibo** [timonweb/django-bulma#34]
I use bulma in django, why Navbar-burger doesn't work, shows on the mobile side, can't come dropdown the menu, thank you!

**Comment by Huanghibo** [comment]
I run django-bulma's demo, the problem also exists.

**Comment by Huanghibo** [comment]
Using this js, Ok! But not bulmanic.
document.addEventListener('DOMContentLoaded', () => {

  // Get all "navbar-burger" elements
  const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

  // Check if there are any navbar burgers
  if ($navbarBurgers.length > 0) {

    // Add a click event on each of them
    $navbarBurgers.forEach( el => {
      el.addEventListener('click', () => {

        // Get the target from the "data-target" attribute
        const target = el.dataset.target;
        const $target = document.getElementById(target);

        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        el.classList.toggle('is-active');
        $target.classList.toggle('is-active');

      });
    });
  }

});

**Comment by timonweb** [comment]
Bulma doesn't provide any js, it's up to a developer to code this part up.
