### ISSUE TITLE
customise  bulma/base.html

### ISSUE THREAD

**Issue by kate2797** [timonweb/django-bulma#38]
Hey, I'm new to Django/Bulma, so sorry if this question is stupid.
I'd like to customise the  bulma/base.html if it is possible, any ideas on how to approach this problem? 

Thank you

**Comment by rarf** [comment]
I was looking for that too...

I solved putting my app import before bulma in settings like:

```
INSTALLED_APPS = [
    'myapp.core',

    'bulma',
]
```

and create a base.html template in my app root template folder.

```
- myapp
  -core
    - templates
      - base.html
```

**Comment by timonweb** [comment]
@rarf yes, that works, but the simple solution is to just put your override under the main `templates` dir as `templates/base.html`, that way you don't have to create a separate app in order to override the base template.
