### ISSUE TITLE
Possible conflict with AllAuth?

### ISSUE THREAD

**Issue by hugoelliott** [timonweb/django-bulma#40]
I'm setting up a Django project using [AllAuth](https://django-allauth.readthedocs.io/en/latest/index.html) for user authentication, and django-bulma to provide styling on forms.

The Signup and Login pages work well, however, when I include "{{form**|bulma**}}" in the Logout form, an error message is generated (pls see attached).  

If I remove the "|bulma" the Logout page functions 

The code on my form is

{% extends '_base.html' %}
{% load bulma_tags %}
{% block content %}

<h1 class="title">Log Out</h1>
<p>Are you sure you want to Log Out?</p>
<form method="POST" action="{% url 'account_logout' %}">
  {% csrf_token %}
  {{form|bulma}}
  <div class="control">
  <br>
  <button type="submit" class="button is-danger">Log Out</button>
  </div>
</form>

{% endblock content %}

<img width="820" alt="error" src="https://user-images.githubusercontent.com/27383708/65332328-c2cd1480-dbbe-11e9-9174-d13475ef7b31.png">

**Comment by sangenispablo** [comment]
How do you use AllAuth, can you give me an example?, is the only thing I need.

**Comment by timonweb** [comment]
The allauth support has been dropped. It's up to a developer to integrate it with bulma now.
