### ISSUE TITLE
lib folder not being copied

### ISSUE THREAD

**Issue by joaodesousa** [timonweb/django-bulma#46]
After running 

`python manage.py copy_bulma_static_into_project`

the folders **sass** and **css** are copied but lib isn't.

**Comment by timonweb** [comment]
The project doesn't have any lib folder, where does it come from?

**Comment by joaodesousa** [comment]
According to the readme,

> 4.1 Copy bulma static files into your project's STATIC_ROOT:
> 
> `python manage.py copy_bulma_static_into_project`
> You should see bulma dir appeared in your STATIC_ROOT. It contains three dirs:
> 
> **lib - where we put original and untouched bulma package, in most cases you shouldn't mess with it**
> sass - this is the place where you can put your own sass code and customize bulma variables
> css - this is where compiled sass output goes, you should link this file in your base.html

**Comment by timonweb** [comment]
aha, this is outdated information, you don't need *lib* anymore, thanks for pointing out, removed from readme.
