### ISSUE TITLE
Error running python manage.py bulma install on Windows

### ISSUE THREAD

**Issue by cpkthompson** [timonweb/django-bulma#9]
File "c:\python\python36-32\Lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by timonweb** [comment]
Hey, thanks for reporting this. Unfortunately, I don't use Windows and have no intention to support it. If you or anyone else knows how to fix the bug, PR is welcome.

**Comment by kryskool** [comment]
Hi @cpkthompson 

I think it cannot find npm, can you add it in your PATH

Regards

**Comment by matukaa** [comment]
After you executed
`python manage.py copy_bulma_static_into_project`

Go to STATIC_ROOT/bulma/sass and try
`npm install bulma`

You need to have npm installed and added to PATH variables I believe. This will create a folder named "node_modules" where you can find all the elements related to bulma

**Comment by gl0ves** [comment]
You can also add **shell=True** to the npm_run function in bulma.py

```
def npm_run(self, commands):
        try:
            subprocess.run(['npm'] + commands, shell=True, cwd=self.bulma_dir)
        except KeyboardInterrupt:
            pass
```

**Comment by LoLL0** [comment]
Hi all, 

I've just noticed that I have the same issue with my Rasp Pi 3. 

FileNotFoundError [Errno 2] no such file or directory 'npm' 

Could anyone try to help me?
